# Dependencies
markdown:         redcarpet
highlights:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Drifts
tagline:          'The new side of electronic music.'
description:      'Bi-weekly electronic music radio show and podcast.'
url:              http://next.drifts.fm

author:
  name:           'William Donaldson'
  url:            https://twitter.com/wonaldson

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/wonaldson/drifts.fm


collections:
- shows

fg-color: "#FFFFFF"
bg-color: "#000000"
link-color: "#FF0000"