# Dependencies
markdown:         redcarpet
highlights:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Drifts
tagline:          'The intelligent side of electronic music.'
description:      'Bi-weekly intelligent electronic music radio show and podcast.'
url:              http://next.drifts.fm

author:
  name:           'William Donaldson'
  url:            https://twitter.com/wonaldson

paginate:         6
paginate_path:    "news/page:num/"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/wonaldson/drifts.fm


collections:
  shows:
    output: true

fg-color: "#FFFFFF"
bg-color: "#000000"
link-color: "#FF0000"