#local
port: 3000


# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Drifts
tagline:          'The intelligent side of electronic music.'
description:      'Bi-weekly intelligent electronic music radio show and podcast.'
url:              'http://next.drifts.fm'

author:
  name:           'William Donaldson'
  url:            'https://twitter.com/wonaldson'

paginate:         6
paginate_path:    "news/page:num/"

encoding:					'utf-8'

# Custom vars
version:          1.0.0

github:
  repo:           'https://github.com/wonaldson/drifts.fm'


collections:
  shows:
    output: true
    permalink: /shows/:path/

# Drifts vars

fg-color: "#0993FF"
bg-color: "#f4f8f2"
link-color: "#268bd2"

cdn-base: "http://cdn.drifts.fm/"
image-base: "images/"
podcast-base: "podcasts/"
image-extension: ".png"
